"""empty message

Revision ID: bc0ba1eab10e
Revises: c417aa8b723c
Create Date: 2016-03-31 17:44:57.980000

"""

# revision identifiers, used by Alembic.
revision = 'bc0ba1eab10e'
down_revision = 'c417aa8b723c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
