"""empty message

Revision ID: d1b3ab43d775
Revises: bc0ba1eab10e
Create Date: 2016-04-01 11:04:21.149000

"""

# revision identifiers, used by Alembic.
revision = 'd1b3ab43d775'
down_revision = 'bc0ba1eab10e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
